pipeline
{
agent any
	stages {
		stage ("Build")
		step	{
		echo "Start Building"
		sh "npm install"
		sh "npm run build"
		echo "Buld Completed"
		

			}
	stage (Deploy)	
		steps{ 
		echo "Strat Deployment on EC2"
		sh "scp -r -o strictcheckingOfKey=No" ./dist/* /home/ubuntu/node-app/"
		sh "npm start"
		echo "Deployment Completed"
		}
	

}
}
